---
title: "IST 5535 | Machine Learning Project: New York-Rent Prices-2020-Zillow Dataset"
author: "Group 2 | Tanner Fry, Sayantan Majumdar, Daren Liu"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: true
---
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
# Clean the environment
rm(list = ls())
```

# Data Exploration

```{r}
zillow.data <- read.csv('../Data/zillow.csv')
str(zillow.data)
# summary(zillow.data)
```

# Data Cleaning

```{r}
zillow.data <- subset(zillow.data, 
                      select = -c(yearBuilt: longitude,
                                  real.estate.provider:commute, latitude))
zillow.data <- na.omit(zillow.data)
# there are two rows in the na removed df where price is blank

transform_price <- function(price, sep = ',') {
  library(qdapRegex)
  
  if (price == '' || is.na(price)) {  # Fixes blank issue
    return(NA) 
  }
  price <- paste(price, '/', sep = '')
  check_plus <- ex_between(price, '$', '+')[[1]]
  check_bracket <- ex_between(price, '$', ')')[[1]]
  check_slash <- ex_between(price, '$', '/')[[1]]
  p <- NA
  if (!is.na(check_plus)) {
    p <- as.numeric(gsub(sep, "", check_plus))
  } else if (!is.na(check_bracket)) {
    p <- as.numeric(gsub(sep, "", check_bracket))
  } else if (!is.na(check_slash)) {
    p <- as.numeric(gsub(sep, "", check_slash))
  }
  return(p)
}

zillow.data$price <- sapply(zillow.data$price, transform_price)
zillow.data <- na.omit(zillow.data)
str(zillow.data)
summary(zillow.data)
write.csv(zillow.data, '../Data/zillow_cleaned.csv', row.names = FALSE)
```

# Data Exploration V2

```{r, fig.height = 5, fig.width = 6}
library(dplyr)
library(psych)
pairs(~ ., data = zillow.data)
```

```{r, fig.height = 7, fig.width = 9}
# Note: may want to remove state?
zillow.data %>% select(c(area, bathrooms, bedrooms, homeStatus, homeType,
                         price, state)) %>% 
pairs.panels(method = "pearson", # correlation method 
                hist.col = "green",
                density = TRUE,  # show density plots 
                ellipses = TRUE # show correlation ellipses
                )
```
## Price of homes have a positively related with the number of bedrooms and bathrooms (at least with most data points via bathrooms. Bathrooms might need to be refined as there seems to be a few outliers). 

## TODO: Figure out if price needs to be numeric for pairs to work properly via analysis

```{r}
hist(zillow.data$bedrooms,
     main = 'Histogram of Bedrooms',
     xlab = 'Bedrooms')
```

```{r}
hist(zillow.data$bathrooms,
     main = 'Histogram of Bathrooms',
     xlab = 'Bathrooms')
```

```{r}
hist(zillow.data$area,
     main = 'Histogram of Area',
     xlab = 'Area')
```

```{r}
hist(zillow.data$price,
     main = 'Histogram of Price',
     xlab = 'Price')
```

